name: ✨ Feature Request
description: Suggest a new feature or improvement for waybar-lyric
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to make waybar-lyric better?
        We’d love to hear it 🚀

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
      placeholder: |
        I find it difficult when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your ideal solution
      placeholder: |
        Add support for...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: |
        Other approaches you’ve thought about
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues and discussions
          required: true
